name: Deploy Web Build to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  export-web:
    runs-on: ubuntu-latest
    name: Web Export
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mkdir -v -p ~/.config/godot/

      - name: Download Godot
        run: |
          wget -q https://downloads.tuxfamily.org/godotengine/4.4.1/Godot_v4.4.1-stable_linux.x86_64.zip
          unzip Godot_v4.4.1-stable_linux.x86_64.zip
          mv Godot_v4.4.1-stable_linux.x86_64 godot

      - name: Download Export Templates
        run: |
          wget -q https://downloads.tuxfamily.org/godotengine/4.4.1/Godot_v4.4.1-stable_export_templates.tpz
          unzip Godot_v4.4.1-stable_export_templates.tpz
          mv templates/* ~/.local/share/godot/export_templates/

      - name: Setup Export Presets
        run: |
          cat > export_presets.cfg << 'EOF'
          [preset.0]

          name="Web"
          platform="Web"
          runnable=true
          dedicated_server=false
          custom_features=""
          export_filter="all_resources"
          include_filter=""
          exclude_filter=""
          export_path="build/index.html"
          encryption_include_filters=""
          encryption_exclude_filters=""
          encrypt_pck=false
          encrypt_directory=false

          [preset.0.options]

          custom_template/debug=""
          custom_template/release=""
          variant/extensions_support=false
          vram_texture_compression/for_desktop=true
          vram_texture_compression/for_mobile=false
          html/export_icon=true
          html/custom_html_shell=""
          html/head_include=""
          html/canvas_resize_policy=2
          html/focus_canvas_on_start=true
          html/experimental_virtual_keyboard=false
          progressive_web_app/enabled=false
          progressive_web_app/offline_page=""
          progressive_web_app/display=1
          progressive_web_app/orientation=0
          progressive_web_app/icon_144x144=""
          progressive_web_app/icon_180x180=""
          progressive_web_app/icon_512x512=""
          progressive_web_app/background_color=Color(0, 0, 0, 1)
          EOF

      - name: Build
        run: |
          mkdir -p build
          ./godot --headless --verbose --export-release "Web" build/index.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: export-web
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
