name: Deploy Web Build to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  export_game:
    runs-on: ubuntu-latest
    name: Export and Deploy
    strategy:
      matrix:
        preset:
          - name: Web
            output: builds/Web/index.html

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Godot CLI
        run: |
          curl -L -o godot.zip https://github.com/godotengine/godot/releases/download/4.4.1-stable/Godot_v4.4.1-stable_linux.x86_64.zip
          unzip godot.zip -d godot
          chmod +x godot/Godot_v4.4.1-stable_linux.x86_64

      - name: Setup export templates and Android build template
        run: |
          curl -L -o templates.tpz https://github.com/godotengine/godot/releases/download/4.4.1-stable/Godot_v4.4.1-stable_export_templates.tpz
          mkdir -p ~/.local/share/godot/export_templates/4.4.1.stable/
          unzip templates.tpz -d ~/.local/share/godot/export_templates/4.4.1.stable/

          # Move nested templates up one level if needed
          if [ -d ~/.local/share/godot/export_templates/4.4.1.stable/templates ]; then
            mv ~/.local/share/godot/export_templates/4.4.1.stable/templates/* ~/.local/share/godot/export_templates/4.4.1.stable/
            rm -rf ~/.local/share/godot/export_templates/4.4.1.stable/templates
          fi

      - name: Export ${{ matrix.preset.name }}
        run: |
          mkdir -p $(dirname "${{ matrix.preset.output }}")

          ./godot/Godot_v4.4.1-stable_linux.x86_64 \
            --headless \
            --path . \
            --export-release "${{ matrix.preset.name }}" "${{ matrix.preset.output }}"

      - name: Deploy Web to GitHub Pages 🚀
        if: matrix.preset.name == 'Web'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: ./builds/Web
